.TH GLMIXER "7" "September 2015" "glmixer" "User Commands"
.SH NAME
glmixer \- Graphic Live Mixer
.SH DESCRIPTION
Real-time video mixing software for live performance.
.SH SYNOPSIS
.B glmixer 
[\-v | \-\-version]\ [\-h | \-\-help]
.IR sessionfile.glm
.SH OPTIONS
.TP
.BR \-v ",  " \-\-version
Show version
.TP
.BR \-h ",  " \-\-help
Show help

